# Generated by Django 5.1.3 on 2024-11-25 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigetZoo', '0002_alter_zoouser_housenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelBooking',
            fields=[
                ('hotelD', models.AutoField(primary_key=True, serialize=False)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('adult', models.IntegerField(default=0, max_length=2)),
                ('child', models.IntegerField(default=0, max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='zooBooking',
            fields=[
                ('zooID', models.AutoField(primary_key=True, serialize=False)),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('adult', models.IntegerField(default=0, max_length=2)),
                ('child', models.IntegerField(default=0, max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creation_data', models.DateTimeField(auto_now_add=True)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
