# Generated by Django 5.1.3 on 2024-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rigetZoo', '0004_alter_hotelbooking_adult_alter_hotelbooking_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoobooking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
